<?php

namespace common\models;

use Yii;

/**
 * This is the model class for table "images".
 *
 * @property integer $id
 * @property integer $newsID
 * @property integer $userID
 * @property integer $date
 * @property string $description
 * @property string $link
 */
class Image extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'images';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['newsID', 'userID', 'date'], 'integer'],
            [['description'], 'string', 'max' => 255],
            [['link'], 'string', 'max' => 128],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'newsID' => 'News ID',
            'userID' => 'User ID',
            'date' => 'Date',
            'description' => 'Description',
            'link' => 'Link',
        ];
    }

    public function beforeSave($insert)
    {
        if($this->isNewRecord){
            $this->date = time();
        }

        if(empty($this->newsID)){
            $this->newsID = 0;
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
