<?php

namespace common\models;

use common\helpers\TranslitHelper;
use Yii;

/**
 * This is the model class for table "menus".
 *
 * @property string $id
 * @property string $name
 * @property string $alias
 *
 * @property MenuItem[] $items
 */
class Menu extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'menus';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'alias'], 'required'],
            [['name'], 'string', 'max' => 255],
            [['alias'], 'string', 'max' => 32],
            [['alias'], 'unique'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'alias' => 'Алиас',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItems()
    {
        return $this->hasMany(MenuItem::className(), ['menuID' => 'id'])->orderBy('order');
    }

    public function beforeSave($insert)
    {
        if(($this->isNewRecord && empty($this->alias)) || ($this->getOldAttribute('name') != $this->name && !$this->isAttributeChanged('alias'))){
            $this->alias = TranslitHelper::to($this->name);
        }

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
